apiVersion: v1
kind: ConfigMap
metadata:
 name: ansible-config
data:
 ansible.cfg: |
   [defaults]
   inventory = inventory/hosts.yml
   host_key_checking = False
   
   [privilege_escalation]
   become = True
   
   [winrm_connection]
   scheme = https
   transport = ntlm
