apiVersion: v1
kind: Secret
metadata:
 name: ansible-secrets
type: Opaque
stringData:
 ansible_user: "your-windows-user"  # Will be encrypted
 ansible_password: "your-password"   # Will be encrypted
 git_ssh_key: |
   -----BEGIN OPENSSH PRIVATE KEY-----
   Your SSH key here
   -----END OPENSSH PRIVATE KEY-----
